/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export declare namespace Register {
  export type VoterDataStruct = { pubKey: BytesLike; hashedId: BytesLike };

  export type VoterDataStructOutput = [string, string] & {
    pubKey: string;
    hashedId: string;
  };
}

export interface RegisterInterface extends utils.Interface {
  functions: {
    "addEligibleVoter(address)": FunctionFragment;
    "addVoter(address)": FunctionFragment;
    "admin()": FunctionFragment;
    "getHashedIDs()": FunctionFragment;
    "getLRSGroup()": FunctionFragment;
    "getVoterData()": FunctionFragment;
    "isRegistrationOpen()": FunctionFragment;
    "sessionID()": FunctionFragment;
    "setRegistrationPeriod(uint256,uint256)": FunctionFragment;
    "setSessionID(string)": FunctionFragment;
    "storeVoterData(bytes,bytes)": FunctionFragment;
    "voterData(uint256)": FunctionFragment;
    "voters(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addEligibleVoter"
      | "addVoter"
      | "admin"
      | "getHashedIDs"
      | "getLRSGroup"
      | "getVoterData"
      | "isRegistrationOpen"
      | "sessionID"
      | "setRegistrationPeriod"
      | "setSessionID"
      | "storeVoterData"
      | "voterData"
      | "voters"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addEligibleVoter",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "addVoter", values: [string]): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getHashedIDs",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLRSGroup",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVoterData",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistrationOpen",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "sessionID", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setRegistrationPeriod",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSessionID",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "storeVoterData",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "voterData",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "voters",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addEligibleVoter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addVoter", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getHashedIDs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLRSGroup",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVoterData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegistrationOpen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sessionID", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setRegistrationPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSessionID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storeVoterData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "voterData", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "voters", data: BytesLike): Result;

  events: {
    "HashedIDStored()": EventFragment;
    "LRSPKStored()": EventFragment;
    "RegistrationPeriodSet()": EventFragment;
    "SessionIDSet()": EventFragment;
    "VoterAdded()": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "HashedIDStored"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LRSPKStored"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RegistrationPeriodSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SessionIDSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "VoterAdded"): EventFragment;
}

export interface HashedIDStoredEventObject {}
export type HashedIDStoredEvent = TypedEvent<[], HashedIDStoredEventObject>;

export type HashedIDStoredEventFilter = TypedEventFilter<HashedIDStoredEvent>;

export interface LRSPKStoredEventObject {}
export type LRSPKStoredEvent = TypedEvent<[], LRSPKStoredEventObject>;

export type LRSPKStoredEventFilter = TypedEventFilter<LRSPKStoredEvent>;

export interface RegistrationPeriodSetEventObject {}
export type RegistrationPeriodSetEvent = TypedEvent<
  [],
  RegistrationPeriodSetEventObject
>;

export type RegistrationPeriodSetEventFilter =
  TypedEventFilter<RegistrationPeriodSetEvent>;

export interface SessionIDSetEventObject {}
export type SessionIDSetEvent = TypedEvent<[], SessionIDSetEventObject>;

export type SessionIDSetEventFilter = TypedEventFilter<SessionIDSetEvent>;

export interface VoterAddedEventObject {}
export type VoterAddedEvent = TypedEvent<[], VoterAddedEventObject>;

export type VoterAddedEventFilter = TypedEventFilter<VoterAddedEvent>;

export interface Register extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RegisterInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addEligibleVoter(
      _voter: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    addVoter(
      _voter: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    admin(overrides?: CallOverrides): Promise<[string]>;

    getHashedIDs(
      overrides?: CallOverrides
    ): Promise<[string[]] & { _hashedIDs: string[] }>;

    getLRSGroup(
      overrides?: CallOverrides
    ): Promise<[string[]] & { _lrs: string[] }>;

    getVoterData(
      overrides?: CallOverrides
    ): Promise<[Register.VoterDataStructOutput[]]>;

    isRegistrationOpen(
      overrides?: CallOverrides
    ): Promise<[boolean] & { isOpen: boolean }>;

    sessionID(overrides?: CallOverrides): Promise<[string]>;

    setRegistrationPeriod(
      _start: BigNumberish,
      _end: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setSessionID(
      _id: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    storeVoterData(
      _hashedID: BytesLike,
      _publicKey: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    voterData(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, string] & { pubKey: string; hashedId: string }>;

    voters(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;
  };

  addEligibleVoter(
    _voter: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  addVoter(
    _voter: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  admin(overrides?: CallOverrides): Promise<string>;

  getHashedIDs(overrides?: CallOverrides): Promise<string[]>;

  getLRSGroup(overrides?: CallOverrides): Promise<string[]>;

  getVoterData(
    overrides?: CallOverrides
  ): Promise<Register.VoterDataStructOutput[]>;

  isRegistrationOpen(overrides?: CallOverrides): Promise<boolean>;

  sessionID(overrides?: CallOverrides): Promise<string>;

  setRegistrationPeriod(
    _start: BigNumberish,
    _end: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setSessionID(
    _id: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  storeVoterData(
    _hashedID: BytesLike,
    _publicKey: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  voterData(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[string, string] & { pubKey: string; hashedId: string }>;

  voters(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  callStatic: {
    addEligibleVoter(_voter: string, overrides?: CallOverrides): Promise<void>;

    addVoter(_voter: string, overrides?: CallOverrides): Promise<void>;

    admin(overrides?: CallOverrides): Promise<string>;

    getHashedIDs(overrides?: CallOverrides): Promise<string[]>;

    getLRSGroup(overrides?: CallOverrides): Promise<string[]>;

    getVoterData(
      overrides?: CallOverrides
    ): Promise<Register.VoterDataStructOutput[]>;

    isRegistrationOpen(overrides?: CallOverrides): Promise<boolean>;

    sessionID(overrides?: CallOverrides): Promise<string>;

    setRegistrationPeriod(
      _start: BigNumberish,
      _end: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setSessionID(_id: string, overrides?: CallOverrides): Promise<void>;

    storeVoterData(
      _hashedID: BytesLike,
      _publicKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    voterData(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, string] & { pubKey: string; hashedId: string }>;

    voters(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "HashedIDStored()"(): HashedIDStoredEventFilter;
    HashedIDStored(): HashedIDStoredEventFilter;

    "LRSPKStored()"(): LRSPKStoredEventFilter;
    LRSPKStored(): LRSPKStoredEventFilter;

    "RegistrationPeriodSet()"(): RegistrationPeriodSetEventFilter;
    RegistrationPeriodSet(): RegistrationPeriodSetEventFilter;

    "SessionIDSet()"(): SessionIDSetEventFilter;
    SessionIDSet(): SessionIDSetEventFilter;

    "VoterAdded()"(): VoterAddedEventFilter;
    VoterAdded(): VoterAddedEventFilter;
  };

  estimateGas: {
    addEligibleVoter(
      _voter: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    addVoter(
      _voter: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    admin(overrides?: CallOverrides): Promise<BigNumber>;

    getHashedIDs(overrides?: CallOverrides): Promise<BigNumber>;

    getLRSGroup(overrides?: CallOverrides): Promise<BigNumber>;

    getVoterData(overrides?: CallOverrides): Promise<BigNumber>;

    isRegistrationOpen(overrides?: CallOverrides): Promise<BigNumber>;

    sessionID(overrides?: CallOverrides): Promise<BigNumber>;

    setRegistrationPeriod(
      _start: BigNumberish,
      _end: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setSessionID(
      _id: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    storeVoterData(
      _hashedID: BytesLike,
      _publicKey: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    voterData(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    voters(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    addEligibleVoter(
      _voter: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    addVoter(
      _voter: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    admin(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getHashedIDs(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getLRSGroup(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getVoterData(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isRegistrationOpen(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    sessionID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setRegistrationPeriod(
      _start: BigNumberish,
      _end: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setSessionID(
      _id: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    storeVoterData(
      _hashedID: BytesLike,
      _publicKey: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    voterData(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    voters(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
