/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IEvoting__factory } from "./IEvoting__factory";
export { IFactoryEvoting__factory } from "./IFactoryEvoting__factory";
